name: Run Backend Tests on grantech-be-dev

on:
  pull_request:
    branches:
      - azure-dev
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: grantech-test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Migrate DB
        env:
          DB_DIALECT: postgres
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: grantech-test
          DB_USER: postgres
          DB_PASSWORD: postgres
        run: npx sequelize db:migrate

      - name: Run tests
        env:
          DB_DIALECT: postgres
          DB_HOST: localhost # You can use `postgres` here if localhost causes issues
          DB_PORT: 5432
          DB_NAME: grantech-test
          DB_USER: postgres
          DB_PASSWORD: postgres
        run: npm test
